### ISSUE TITLE
Make windows binaries

### ISSUE THREAD

**Issue by trimechee** [lampuiho/TUFA152021BatteryChargeLimiter#1]
your software is wonderful! thank you very much! Please, I am a neophyte and also a lot of windows 10 users who do not know how to import and manipulate scripts, it would be great please to make windows binaries to install it in a classic way or a simplified tutorial or video tutorial how to operate this script that I can't download it, I don't know how to download it because I see the releases section and I can't see anything .....

Thanks for your help !

**Comment by lampuiho** [comment]
To download all files in a repository, use code->download zip.
Task Scheduler, Just use the first result from google search.
https://technoresult.com/import-or-export-tasks-from-the-task-scheduler-in-windows-10/
Or make a bat file with the command:
schtasks /create /xml “%~dp0Battery Charge Limiter.xml” /tn “\”
Windows has its own installer. I won't make a installer because I use my apps in a portable way. I install things to a path I specify and that can be used in another system. That's the very reason I don't use UWP in the first place.

**Comment by trimechee** [comment]
Great ! Thank you very much for your precious help and this wonderful script :) another question please : is this script compatible with other Asus models or older models ? and is there a possibility to set the battery limit to 80% for example ?

**Comment by lampuiho** [comment]
You can change 60 (search for 0x3C) to 80 (0x50) in the source and compile it with mingw64. mingw64 is portable so nothing to install.
